### ISSUE TITLE
Safari - Zoom Property Causes Miscalculation of Line Position

### ISSUE THREAD

**Issue by kdagnan** [AhmedAyachi/LinkerLine#13]
I have created a large flow chart with zoom capabilities, and I am using the CSS `zoom` property to accomplish this. When the user zooms, I update the CSS property, remove all of the lines, and add them all back in.

This has worked great on Chrome & Firefox, but I recently received a bug report from a user saying it causes issues in Safari. I've tested and confirmed this issue in both MacOS and iOS safari:

Zoom: 1
![Image](https://github.com/user-attachments/assets/210b37b6-7e04-42bf-9cfe-60bac6d78fd4)

Zoom: 1.1
![Image](https://github.com/user-attachments/assets/9003a6d6-91f1-46b0-a346-1cbaa4cbef57)

It appears that somehow the calculations are being messed up.

I realize this is probably not a common use case, but any help in getting this to work as expected in Safari would be appreciated. Or any assistance on what I could tell Safari the issue is.

**Comment by AhmedAyachi** [comment]
can you share a piece of code of your implementaion via CodePen or similar sites.

**Comment by kdagnan** [comment]
@AhmedAyachi https://codepen.io/kdagnan/pen/wBBXVbq

Works as I'd expect in Chrome & Firefox, but not in Safari

**Comment by AhmedAyachi** [comment]
@kdagnan  Ok, now I see, but can't you just place the line, line.start and line.end in a div container and zoom that one ?
Just a tip, when zooming, instead of removing and replacing the line, just call line.position.

**Comment by AhmedAyachi** [comment]
@kdagnan check out the fix pushed to the beta branch, not a perfect fix but hope that is enough for your case.

**Comment by kdagnan** [comment]
@AhmedAyachi Zooming the parent itself doesn't seem to work in any browser. Needs to be a child of the parent for some reason.

And beta branch does not appear to fix it, I appreciate the help!

**Comment by AhmedAyachi** [comment]
@kdagnan As I told you, its not a perfect fix, to get it to work, you can alter your code as follows:
```
let zoom = 1;
function zoomIn(){
    zoom+=0.1;
    line.start.style.zoom=line.end.style.zoom=zoom;
    line.position();
}
```
No need to reinstantiate the line, just call position.
This code should make zoom properly work on safari.

**Comment by AhmedAyachi** [comment]
@kdagnan hello, I wanted to tackle this issue as when setting a zoom value on the start/end elements, the line position does not shift on Chrome/Edge/Firefox and only becomes incorrect on Safari. 
Trying to make the behavior consistent on most major browsers, I added an isSafari block in the LinkerLine.position method, and it seemed to fix it at the time.
But today, I tested it and it seems like safari has made an update or a fix as that code block is no longer required and it actually breaks the positioning.
Could you please confirm that for me before I apply those changes.
Thanks.

**Comment by kdagnan** [comment]
> [@kdagnan](https://github.com/kdagnan) hello, I wanted to tackle this issue as when setting a zoom value on the start/end elements, the line position does not shift on Chrome/Edge/Firefox and only becomes incorrect on Safari. Trying to make the behavior consistent on most major browsers, I added an isSafari block in the LinkerLine.position method, and it seemed to fix it at the time. But today, I tested it and it seems like safari has made an update or a fix as that code block is no longer required and it actually breaks the positioning. Could you please confirm that for me before I apply those changes. Thanks.

I did notice while verifying our Firefox issue fix that Safari Zoom does seem to be behaving as expected on the most recent release version (1.6.2). Just verified again with Safari Version 26.5.2 (21624.2.5.11.8) _and_ Safari Technology Preview Release 249 (WebKit 21626.1.1). I don't believe any changes are required, it is behaving as it behaves on Chrome/Firefox.
